define(function(){function z(m,z){function c(a,b,e){m.WeixinJSBridge?WeixinJSBridge.invoke(a,G(b),function(b){I(a,b,e)}):v(a,e)}function r(a,b,e){m.WeixinJSBridge?WeixinJSBridge.on(a,function(c){e&&e.trigger&&e.trigger(c);I(a,c,b)}):e?v(a,e):v(a,b)}function G(a){return a=a||{},a.appId=k.appId,a.verifyAppId=k.appId,a.verifySignType="sha1",a.verifyTimestamp=k.timestamp+"",a.verifyNonceStr=k.nonceStr,a.verifySignature=k.signature,a}function I(a,b,e){var c;delete b.err_code;delete b.err_desc;delete b.err_detail;
var g=b.errMsg;if(!g){g=b.err_msg;delete b.err_msg;var d,f,h=A[a];g=(h&&(a=h),d="ok",g&&(f=g.indexOf(":"),d=g.substring(f+1),"confirm"==d&&(d="ok"),"failed"==d&&(d="fail"),-1!=d.indexOf("failed_")&&(d=d.substring(7)),-1!=d.indexOf("fail_")&&(d=d.substring(5)),d=d.replace(/_/g," "),d=d.toLowerCase(),("access denied"==d||"no permission to execute"==d)&&(d="permission denied"),"config"==a&&"function not exist"==d&&(d="ok"),""==d&&(d="fail")),a+":"+d);b.errMsg=g}switch(e=e||{},e._complete&&(e._complete(b),
delete e._complete),g=b.errMsg||"",k.debug&&!e.isInnerInvoke,c=g.indexOf(":"),g.substring(c+1)){case "ok":e.success&&e.success(b);break;case "cancel":e.cancel&&e.cancel(b);break;default:e.fail&&e.fail(b)}e.complete&&e.complete(b)}function J(a){var b;if(a){var e=0;for(b=a.length;b>e;++e){var c=a[e];(c=h[c])&&(a[e]=c)}return a}}function v(a,b){!k.debug||b&&b.isInnerInvoke||b&&b._complete&&delete b._complete}function N(){0!=f.preVerifyState&&(K||L||k.debug||"6.0.2">w||0>f.systemType||B||(B=!0,f.appId=
k.appId,f.initTime=n.initEndTime-n.initStartTime,f.preVerifyTime=n.preVerifyEndTime-n.preVerifyStartTime,t.getNetworkType({isInnerInvoke:!0,success:function(a){f.networkType=a.networkType;a="http://open.weixin.qq.com/sdk/report?v="+f.version+"&o="+f.preVerifyState+"&s="+f.systemType+"&c="+f.clientVersion+"&a="+f.appId+"&n="+f.networkType+"&i="+f.initTime+"&p="+f.preVerifyTime+"&u="+f.url;(new Image).src=a}})))}function M(a){C&&(m.WeixinJSBridge?a():x.addEventListener&&x.addEventListener("WeixinJSBridgeReady",
a,!1))}function O(){t.invoke||(t.invoke=function(a,b,e){m.WeixinJSBridge&&WeixinJSBridge.invoke(a,G(b),e)},t.on=function(a,b){m.WeixinJSBridge&&WeixinJSBridge.on(a,b)})}var h,A,x,u,p,D,K,L,C,y,E,w,B,F,n,f,k,l,q,t;if(!m.jWeixin)return h={config:"preVerifyJSAPI",onMenuShareTimeline:"menu:share:timeline",onMenuShareAppMessage:"menu:share:appmessage",onMenuShareQQ:"menu:share:qq",onMenuShareWeibo:"menu:share:weiboApp",onMenuShareQZone:"menu:share:QZone",previewImage:"imagePreview",getLocation:"geoLocation",
openProductSpecificView:"openProductViewWithPid",addCard:"batchAddCard",openCard:"batchViewCard",chooseWXPay:"getBrandWCPayRequest"},A=function(){var a,b={};for(a in h)b[h[a]]=a;return b}(),x=m.document,u=x.title,p=navigator.userAgent.toLowerCase(),D=navigator.platform.toLowerCase(),K=!(!D.match("mac")&&!D.match("win")),L=-1!=p.indexOf("wxdebugger"),C=-1!=p.indexOf("micromessenger"),y=-1!=p.indexOf("android"),E=-1!=p.indexOf("iphone")||-1!=p.indexOf("ipad"),w=function(){var a=p.match(/micromessenger\/(\d+\.\d+\.\d+)/)||
p.match(/micromessenger\/(\d+\.\d+)/);return a?a[1]:""}(),B=!1,F=!1,n={initStartTime:(new Date).getTime(),initEndTime:0,preVerifyStartTime:0,preVerifyEndTime:0},f={version:1,appId:"",initTime:0,preVerifyTime:0,networkType:"",preVerifyState:1,systemType:E?1:y?2:-1,clientVersion:w,url:encodeURIComponent(location.href)},k={},l={_completes:[]},q={state:0,data:{}},M(function(){n.initEndTime=(new Date).getTime()}),t={config:function(a){k=a;v("config",a);var b=!1===k.check?!1:!0;M(function(){var a;if(b)c(h.config,
{verifyJsApiList:J(k.jsApiList)},function(){l._complete=function(a){n.preVerifyEndTime=(new Date).getTime();q.state=1;q.data=a};l.success=function(){f.preVerifyState=0};l.fail=function(a){l._fail?l._fail(a):q.state=-1};var a=l._completes;return a.push(function(){N()}),l.complete=function(){for(var b=0,e=a.length;e>b;++b)a[b]();l._completes=[]},l}()),n.preVerifyStartTime=(new Date).getTime();else{q.state=1;var H=l._completes;var g=0;for(a=H.length;a>g;++g)H[g]();l._completes=[]}});k.beta&&O()},ready:function(a){0!=
q.state?a():(l._completes.push(a),!C&&k.debug&&a())},error:function(a){"6.0.2">w||F||(F=!0,-1==q.state?a(q.data):l._fail=a)},checkJsApi:function(a){c("checkJsApi",{jsApiList:J(a.jsApiList)},function(){return a._complete=function(a){if(y){var b=a.checkResult;b&&(a.checkResult=JSON.parse(b))}var c;b=a.checkResult;for(c in b)(a=A[c])&&(b[a]=b[c],delete b[c])},a}())},onMenuShareTimeline:function(a){r(h.onMenuShareTimeline,{complete:function(){c("shareTimeline",{title:a.title||u,desc:a.title||u,img_url:a.imgUrl||
"",link:a.link||location.href,type:a.type||"link",data_url:a.dataUrl||""},a)}},a)},onMenuShareAppMessage:function(a){r(h.onMenuShareAppMessage,{complete:function(){c("sendAppMessage",{title:a.title||u,desc:a.desc||"",link:a.link||location.href,img_url:a.imgUrl||"",type:a.type||"link",data_url:a.dataUrl||""},a)}},a)},onMenuShareQQ:function(a){r(h.onMenuShareQQ,{complete:function(){c("shareQQ",{title:a.title||u,desc:a.desc||"",img_url:a.imgUrl||"",link:a.link||location.href},a)}},a)},onMenuShareWeibo:function(a){r(h.onMenuShareWeibo,
{complete:function(){c("shareWeiboApp",{title:a.title||u,desc:a.desc||"",img_url:a.imgUrl||"",link:a.link||location.href},a)}},a)},onMenuShareQZone:function(a){r(h.onMenuShareQZone,{complete:function(){c("shareQZone",{title:a.title||u,desc:a.desc||"",img_url:a.imgUrl||"",link:a.link||location.href},a)}},a)},startRecord:function(a){c("startRecord",{},a)},stopRecord:function(a){c("stopRecord",{},a)},onVoiceRecordEnd:function(a){r("onVoiceRecordEnd",a)},playVoice:function(a){c("playVoice",{localId:a.localId},
a)},pauseVoice:function(a){c("pauseVoice",{localId:a.localId},a)},stopVoice:function(a){c("stopVoice",{localId:a.localId},a)},onVoicePlayEnd:function(a){r("onVoicePlayEnd",a)},uploadVoice:function(a){c("uploadVoice",{localId:a.localId,isShowProgressTips:0==a.isShowProgressTips?0:1},a)},downloadVoice:function(a){c("downloadVoice",{serverId:a.serverId,isShowProgressTips:0==a.isShowProgressTips?0:1},a)},translateVoice:function(a){c("translateVoice",{localId:a.localId,isShowProgressTips:0==a.isShowProgressTips?
0:1},a)},chooseImage:function(a){c("chooseImage",{scene:"1|2",count:a.count||9,sizeType:a.sizeType||["original","compressed"],sourceType:a.sourceType||["album","camera"]},function(){return a._complete=function(a){if(y){var b=a.localIds;b&&(a.localIds=JSON.parse(b))}},a}())},previewImage:function(a){c(h.previewImage,{current:a.current,urls:a.urls},a)},uploadImage:function(a){c("uploadImage",{localId:a.localId,isShowProgressTips:0==a.isShowProgressTips?0:1},a)},downloadImage:function(a){c("downloadImage",
{serverId:a.serverId,isShowProgressTips:0==a.isShowProgressTips?0:1},a)},getNetworkType:function(a){c("getNetworkType",{},function(){return a._complete=function(a){var b,c,g=a.errMsg;if(a.errMsg="getNetworkType:ok",b=a.subtype,delete a.subtype,b)a.networkType=b;else switch(c=g.indexOf(":"),b=g.substring(c+1)){case "wifi":case "edge":case "wwan":a.networkType=b;break;default:a.errMsg="getNetworkType:fail"}},a}())},openLocation:function(a){c("openLocation",{latitude:a.latitude,longitude:a.longitude,
name:a.name||"",address:a.address||"",scale:a.scale||28,infoUrl:a.infoUrl||""},a)},getLocation:function(a){a=a||{};c(h.getLocation,{type:a.type||"wgs84"},function(){return a._complete=function(a){delete a.type},a}())},hideOptionMenu:function(a){c("hideOptionMenu",{},a)},showOptionMenu:function(a){c("showOptionMenu",{},a)},closeWindow:function(a){a=a||{};c("closeWindow",{},a)},hideMenuItems:function(a){c("hideMenuItems",{menuList:a.menuList},a)},showMenuItems:function(a){c("showMenuItems",{menuList:a.menuList},
a)},hideAllNonBaseMenuItem:function(a){c("hideAllNonBaseMenuItem",{},a)},showAllNonBaseMenuItem:function(a){c("showAllNonBaseMenuItem",{},a)},scanQRCode:function(a){a=a||{};c("scanQRCode",{needResult:a.needResult||0,scanType:a.scanType||["qrCode","barCode"]},function(){return a._complete=function(a){var b,c;E&&(b=a.resultStr,b&&(c=JSON.parse(b),a.resultStr=c&&c.scan_code&&c.scan_code.scan_result))},a}())},openProductSpecificView:function(a){c(h.openProductSpecificView,{pid:a.productId,view_type:a.viewType||
0,ext_info:a.extInfo},a)},addCard:function(a){var b,e=a.cardList,f=[];var g=0;for(b=e.length;b>g;++g){var d=e[g];d={card_id:d.cardId,card_ext:d.cardExt};f.push(d)}c(h.addCard,{card_list:f},function(){return a._complete=function(a){var b,c=a.card_list;if(c){c=JSON.parse(c);var e=0;for(b=c.length;b>e;++e){var d=c[e];d.cardId=d.card_id;d.cardExt=d.card_ext;d.isSuccess=d.is_succ?!0:!1;delete d.card_id;delete d.card_ext;delete d.is_succ}a.cardList=c;delete a.card_list}},a}())},chooseCard:function(a){c("chooseCard",
{app_id:k.appId,location_id:a.shopId||"",sign_type:a.signType||"SHA1",card_id:a.cardId||"",card_type:a.cardType||"",card_sign:a.cardSign,time_stamp:a.timestamp+"",nonce_str:a.nonceStr},function(){return a._complete=function(a){a.cardList=a.choose_card_info;delete a.choose_card_info},a}())},openCard:function(a){var b,e=a.cardList,f=[];var g=0;for(b=e.length;b>g;++g){var d=e[g];d={card_id:d.cardId,code:d.code};f.push(d)}c(h.openCard,{card_list:f},a)},chooseWXPay:function(a){c(h.chooseWXPay,{timeStamp:a.timestamp+
"",nonceStr:a.nonceStr,"package":a.package,paySign:a.paySign,signType:a.signType||"SHA1"},a)}},z&&(m.wx=m.jWeixin=t),t}return function(){z(window,!0)}});